proxy: proxySet
check: true
socksHost: socksProxyHost
host: 127.0.0.1
socksPort: socksProxyPort
port: 9150
botUserName: MyFirstRomanBot
token: 1174132795:AAHHKUaEFuH-6rNuHyk5B710tUZ59wJ-bSE
checkFlag: added
pathThePhoto: C:/woman_bag/
typeFilePng: .png
typeFileMp4: .mp4

